export const data = [
  {
    id: 1,
    title: "Big Mac",
    price: 2,
    image: "/bigmac.jpg",
  },
  {
    id: 2,
    title: "Flip Flops",
    price: 3,
    image: "/flipflops.jpg",
  },
  {
    id: 3,
    title: "Coca-Cola Pack",
    price: 5,
    image: "/cocacolapack.jpg",
  },
  {
    id: 4,
    title: "Movie Ticket",
    price: 12,
    image: "/movieticket.jpg",
  },
  {
    id: 5,
    title: "Book",
    price: 15,
    image: "/book.jpg",
  },
  {
    id: 6,
    title: "Lobster Dinner",
    price: 45,
    image: "/lobsterdinner.jpg",
  },
  {
    id: 7,
    title: "Video Game",
    price: 60,
    image: "/videogame.jpg",
  },
  {
    id: 8,
    title: "Amazon Echo",
    price: 99,
    image: "/amazonecho.jpg",
  },
  {
    id: 9,
    title: "Year Of Netflix",
    price: 100,
    image: "/netflix.jpg",
  },
  {
    id: 10,
    title: "Air Jordans",
    price: 125,
    image: "/airjordans.jpg",
  },
  {
    id: 11,
    title: "Airpods",
    price: 199,
    image: "/airpods.jpg",
  },
  {
    id: 12,
    title: "Gaming Console",
    price: 299,
    image: "/gamingconsole.jpg",
  },
  {
    id: 13,
    title: "Drone",
    price: 350,
    image: "/drone.jpg",
  },
  {
    id: 14,
    title: "Smartphone",
    price: 699,
    image: "/smartphone.jpg",
  },
  {
    id: 15,
    title: "Bike",
    price: 800,
    image: "/bike.jpg",
  },
  {
    id: 16,
    title: "Kitten",
    price: 1500,
    image: "/kitten.jpg",
  },
  {
    id: 17,
    title: "Puppy",
    price: 1500,
    image: "/puppy.jpg",
  },
  {
    id: 18,
    title: "Auto Rickshaw",
    price: 2300,
    image: "/autorickshaw.jpg",
  },
  {
    id: 19,
    title: "Horse",
    price: 2500,
    image: "/horse.jpg",
  },
  {
    id: 20,
    title: "Acre Of Farmland",
    price: 3000,
    image: "/farmland.jpg",
  },
  {
    id: 21,
    title: "Designer Handbag",
    price: 5500,
    image: "/handbag.jpg",
  },
  {
    id: 22,
    title: "Hot Tub",
    price: 6000,
    image: "/hottub.jpg",
  },
  {
    id: 23,
    title: "Luxury Wine",
    price: 7000,
    image: "/wine.jpg",
  },
  {
    id: 24,
    title: "Diamond Ring",
    price: 10000,
    image: "/ring.jpg",
  },
  {
    id: 25,
    title: "Jet Ski",
    price: 12000,
    image: "/jetski.jpg",
  },
  {
    id: 26,
    title: "Rolex",
    price: 15000,
    image: "/rolex.jpg",
  },
  {
    id: 27,
    title: "Ford F-150",
    price: 30000,
    image: "/fordf.jpg",
  },
  {
    id: 28,
    title: "Tesla",
    price: 75000,
    image: "/tesla.jpg",
  },
  {
    id: 29,
    title: "Monster Truck",
    price: 150000,
    image: "/truck.jpg",
  },
  {
    id: 30,
    title: "Ferrari",
    price: 250000,
    image: "/ferrari.jpg",
  },
  {
    id: 31,
    title: "Single Family Home",
    price: 300000,
    image: "/home.jpg",
  },
  {
    id: 32,
    title: "Gold Bar",
    price: 700000,
    image: "/gold.jpg",
  },
  {
    id: 33,
    title: "McDonalds Franchise",
    price: 1500000,
    image: "/mcdonalds.jpg",
  },
  {
    id: 34,
    title: "Superbowl Ad",
    price: 5250000,
    image: "/superbowl.jpg",
  },
  {
    id: 35,
    title: "Yacht",
    price: 7500000,
    image: "/yacht.jpg",
  },
  {
    id: 36,
    title: "M1 Abrams",
    price: 8000000,
    image: "/m1abrams.jpg",
  },
  {
    id: 37,
    title: "Formula 1 Car",
    price: 15000000,
    image: "/formula1.jpg",
  },
  {
    id: 38,
    title: "Apache Helicopter",
    price: 31000000,
    image: "/helicopter.jpg",
  },
  {
    id: 39,
    title: "Mansion",
    price: 45000000,
    image: "/mansion.jpg",
  },
  {
    id: 40,
    title: "Make a Movie",
    price: 100000000,
    image: "/movie.jpg",
  },
  {
    id: 41,
    title: "Boeing 747",
    price: 1500000,
    image: "/boeing.jpg",
  },
  {
    id: 42,
    title: "Mona Lisa",
    price: 780000000,
    image: "/monalisa.jpg",
  },
  {
    id: 43,
    title: "Skyscraper",
    price: 850000000,
    image: "/skyscraper.jpg",
  },
  {
    id: 44,
    title: "Cruise Ship",
    price: 930000000,
    image: "/cruiseship.jpg",
  },
  {
    id: 45,
    title: "NBA Team",
    price: 2120000000,
    image: "/nbateam.jpg",
  },
];
